version: '3.9'
services:
  rich-h2h-simulator:
    build: .
    container_name: rich-h2h-simulator
    ports:
      - '8099:8099'
    environment:
      SIM_SYSTEM_CONFIG: /app/config/system.json
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./fixtures:/app/fixtures
    restart: unless-stopped
